PROGRAM = ws2811ctl
EXTRA_COMPONENTS = extras/dhcpserver extras/rboot-ota extras/libesphttpd

ESP_IP ?= 192.168.1.4

#Tag for OTA images. 0-27 characters. Change to eg your projects title.
LIBESPHTTPD_OTA_TAGNAME ?= $(PROGRAM)

LIBESPHTTPD_MAX_CONNECTIONS ?= 8
LIBESPHTTPD_STACKSIZE ?= 1024

PROGRAM_CFLAGS += -DFREERTOS -DLIBESPHTTPD_OTA_TAGNAME="\"$(LIBESPHTTPD_OTA_TAGNAME)\"" -DFLASH_SIZE=$(FLASH_SIZE)
EXTRA_CFLAGS += -DMEMP_NUM_NETCONN=$(LIBESPHTTPD_MAX_CONNECTIONS) -DLWIP_IPV6=1 -Wno-parentheses
EXTRA_CXXFLAGS += -DMEMP_NUM_NETCONN=$(LIBESPHTTPD_MAX_CONNECTIONS) -DLIBESPHTTPD_OTA_TAGNAME="\"$(LIBESPHTTPD_OTA_TAGNAME)\"" -DFLASH_SIZE=$(FLASH_SIZE)  -DLWIP_IPV6=1 -Wno-parentheses -std=gnu++11 -fno-threadsafe-statics

include ../../common.mk
